set(_CATKIN_CURRENT_PACKAGE "qt_ros_demo01")
set(qt_ros_demo01_VERSION "0.1.0")
set(qt_ros_demo01_MAINTAINER "lj <menyao@gmail.com>")
set(qt_ros_demo01_PACKAGE_FORMAT "1")
set(qt_ros_demo01_BUILD_DEPENDS "qt_build" "roscpp" "libqt5-dev" "std_msgs" "rosmsg" "message_generation")
set(qt_ros_demo01_BUILD_EXPORT_DEPENDS "qt_build" "roscpp" "libqt5-dev" "std_msgs" "rosmsg" "message_runtime")
set(qt_ros_demo01_BUILDTOOL_DEPENDS "catkin")
set(qt_ros_demo01_BUILDTOOL_EXPORT_DEPENDS )
set(qt_ros_demo01_EXEC_DEPENDS "qt_build" "roscpp" "libqt5-dev" "std_msgs" "rosmsg" "message_runtime")
set(qt_ros_demo01_RUN_DEPENDS "qt_build" "roscpp" "libqt5-dev" "std_msgs" "rosmsg" "message_runtime")
set(qt_ros_demo01_TEST_DEPENDS )
set(qt_ros_demo01_DOC_DEPENDS )
set(qt_ros_demo01_URL_WEBSITE "")
set(qt_ros_demo01_URL_BUGTRACKER "")
set(qt_ros_demo01_URL_REPOSITORY "")
set(qt_ros_demo01_DEPRECATED "")