// Generated by gencpp from file qt_ros_demo01/Arm.msg
// DO NOT EDIT!


#ifndef QT_ROS_DEMO01_MESSAGE_ARM_H
#define QT_ROS_DEMO01_MESSAGE_ARM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <qt_ros_demo01/Joint.h>

namespace qt_ros_demo01
{
template <class ContainerAllocator>
struct Arm_
{
  typedef Arm_<ContainerAllocator> Type;

  Arm_()
    : joint()  {
    }
  Arm_(const ContainerAllocator& _alloc)
    : joint(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::qt_ros_demo01::Joint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::qt_ros_demo01::Joint_<ContainerAllocator> >> _joint_type;
  _joint_type joint;





  typedef boost::shared_ptr< ::qt_ros_demo01::Arm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qt_ros_demo01::Arm_<ContainerAllocator> const> ConstPtr;

}; // struct Arm_

typedef ::qt_ros_demo01::Arm_<std::allocator<void> > Arm;

typedef boost::shared_ptr< ::qt_ros_demo01::Arm > ArmPtr;
typedef boost::shared_ptr< ::qt_ros_demo01::Arm const> ArmConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qt_ros_demo01::Arm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qt_ros_demo01::Arm_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qt_ros_demo01::Arm_<ContainerAllocator1> & lhs, const ::qt_ros_demo01::Arm_<ContainerAllocator2> & rhs)
{
  return lhs.joint == rhs.joint;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qt_ros_demo01::Arm_<ContainerAllocator1> & lhs, const ::qt_ros_demo01::Arm_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qt_ros_demo01

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::qt_ros_demo01::Arm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_ros_demo01::Arm_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_ros_demo01::Arm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_ros_demo01::Arm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_ros_demo01::Arm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_ros_demo01::Arm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qt_ros_demo01::Arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b46d7c4342769b3898ee5c56a7392dd2";
  }

  static const char* value(const ::qt_ros_demo01::Arm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb46d7c4342769b38ULL;
  static const uint64_t static_value2 = 0x98ee5c56a7392dd2ULL;
};

template<class ContainerAllocator>
struct DataType< ::qt_ros_demo01::Arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qt_ros_demo01/Arm";
  }

  static const char* value(const ::qt_ros_demo01::Arm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qt_ros_demo01::Arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Joint[] joint\n"
"================================================================================\n"
"MSG: qt_ros_demo01/Joint\n"
"int32 id\n"
"int32 run_time\n"
"float32 angle\n"
;
  }

  static const char* value(const ::qt_ros_demo01::Arm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qt_ros_demo01::Arm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Arm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qt_ros_demo01::Arm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qt_ros_demo01::Arm_<ContainerAllocator>& v)
  {
    s << indent << "joint[]" << std::endl;
    for (size_t i = 0; i < v.joint.size(); ++i)
    {
      s << indent << "  joint[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::qt_ros_demo01::Joint_<ContainerAllocator> >::stream(s, indent + "    ", v.joint[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // QT_ROS_DEMO01_MESSAGE_ARM_H
